---
title: "HW 5"
author: "QiLu"
date: "11/9/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Problem 1

```{r}
library(tidyverse)
library(readr)
library(dplyr)
library(rvest)


set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

```

output = vector("list", length = 4)


```{r}
fill_in = function(x) {

  if (is.numeric(x)){
    x_changed = x %>% replace_na(mean(x, na.rm=TRUE))
}
  else if(is.character(x)){
  x_changed = replace_na(x,"virginica")
 
  }
  
  tibble(x_changed)
}
```




```{r}
output = vector("list", length = 5)
output = bind_cols(map(iris_with_missing, fill_in))
output

```
 
 
### Problem 2


```{r, message=FALSE}
data_import = list.files(pattern="*.csv", recursive = TRUE) %>% 
  purrr::map(~read_csv(.)) %>% 
  bind_rows(.id = "id")
data_import$con_exp = "exp"
data_import$id = as.numeric(data_import$id)


data_import$con_exp = replace(data_import$con_exp, data_import$id < 11, "con")

data_import_plot = pivot_longer(data_import,week_1:week_8,names_to = "week", values_to = "number") %>% 
  group_by(id,week)

```

```{r}
data_import_plot %>% 
ggplot(aes(x = week, y = number, group = id, color = id)) +
  geom_point() + geom_line(aes(color = id))
```

The difference between control arm and experimental is slightly. In addition, experimental arm increased as the week increased.
  
  
### Problem 3

```{r}
sim_regression = function(n = 100, beta0 = 2, beta1 = 0) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, sqrt(50))
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  broom::tidy(ls_fit) %>%
    filter(term == "x") %>%
    select(estimate, p.value)

}
```

```{r}
output_0 = rerun(100, sim_regression(n = 30)) %>% 
  bind_rows()

output_0
```


For plot part
```{r}
sim_output =  map_df(.x = 0:6, ~ rerun(100, sim_regression(n = 30, beta1 = .x) %>% 
          mutate(beta1 = .x)) %>% 
          bind_rows()
)

sim_plot = sim_output %>%
  mutate(
    reject = ifelse(p.value < 0.05, 1, 0)
  ) %>%
  group_by(beta1) %>%
  summarize(propor = mean(reject)) 

sim_plot$beta1 = as.factor(sim_plot$beta1)
```

```{r}
ggplot(sim_plot, aes(x = beta1, y = propor, fill = beta1, alpha = 0.5)) +
  geom_histogram(stat = "identity") +
  labs(
    x = "Beta1",
    y = "Proportion"
  )
```

As we can see from the graph, beta1 is postive correlation to proportion, that is to say, the effect size is proportional to power.
  
  
```{r}
sim_mean = sim_output %>%
  group_by(beta1) %>%
  summarize(est_mean = mean(estimate)) %>%
  mutate(
    ind = "all"
  )
sim_mean$beta1 = as.factor(sim_mean$beta1)
```


```{r}
sim_rejected_mean <- sim_output %>%
  filter(p.value < 0.05) %>%
  group_by(beta1) %>%
  summarize(est_mean = mean(estimate)) %>%
  mutate(
    ind = "rejected"
  )
sim_rejected_mean$beta1 = as.factor(sim_rejected_mean$beta1)
```


```{r}
plot_data = bind_rows(sim_mean, sim_rejected_mean)

ggplot(plot_data, aes(x = beta1, y = est_mean, group = ind, color = ind)) +
  geom_point() + geom_line() +
  labs(
    x = "True Beta1",
    y = "Average of Estimated Beta1"
  )
```






